name: notificare_assets
description: Notificare Assets Flutter Plugin
version: 3.1.1
homepage: https://notificare.com
documentation: https://docs.notifica.re/sdk/v3/flutter/setup
repository: https://github.com/Notificare/notificare-sdk-flutter/tree/main/notificare_assets

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.4.0
  notificare: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.0.0
  json_serializable: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        package: re.notifica.assets.flutter
        pluginClass: NotificareAssetsPlugin
      ios:
        pluginClass: NotificareAssetsPlugin
