name: notificare_inbox
description: "Notificare Inbox Flutter Plugin: Apps with a built-in message inbox enjoy higher conversions due to its nature of keeping messages around for user access."
version: 3.9.0
homepage: https://notificare.com
documentation: https://docs.notifica.re/sdk/v3/flutter/setup/
repository: https://github.com/Notificare/notificare-sdk-flutter/tree/main/notificare_inbox

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.6.0
  notificare: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.0.0
  json_serializable: ^6.3.0

flutter:
  plugin:
    platforms:
      android:
        package: re.notifica.inbox.flutter
        pluginClass: NotificareInboxPlugin
      ios:
        pluginClass: NotificareInboxPlugin
