name: notificare_user_inbox
description: "Notificare User Inbox Flutter Plugin: Provide your users with a single inbox accessible across all their devices."
version: 4.0.1
homepage: https://notificare.com
documentation: https://docs.notifica.re/sdk/v4/flutter/setup/
repository: https://github.com/Notificare/notificare-sdk-flutter/tree/main/notificare_user_inbox

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.9.0
  notificare: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.0.0
  json_serializable: ^6.3.0

flutter:
  plugin:
    platforms:
      android:
        package: re.notifica.inbox.user.flutter
        pluginClass: NotificareUserInboxPlugin
      ios:
        pluginClass: NotificareUserInboxPlugin
