name: notificare_push
description: Notificare Push Flutter Plugin
version: 3.0.0-alpha.1
author: Notificare
homepage: https://notificare.com

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.0.1
  notificare:
    path: "../notificare"

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.12.2
  json_serializable: ^4.1.0

flutter:
  plugin:
    platforms:
      android:
        package: re.notifica.push.flutter
        pluginClass: NotificarePushPlugin
      ios:
        pluginClass: NotificarePushPlugin
